-- ============================================================================
-- Carga inicial: as coleções e as peças da planilha (acervo/acervo.xlsx).
-- Gerado por `npm run seed` em 25/09/2026, 03:23:46. Não edite à mão.
--
-- Rode no SQL Editor do Supabase DEPOIS do migrations/001_esquema.sql.
-- Pode rodar de novo: o que já existe (mesmo slug, mesmo número) é pulado.
-- ============================================================================

insert into public.colecoes (slug, nome, descricao, ordem) values
  ('devocao', 'Devoção', 'Imagens sacras e oratórios.', 1),
  ('parede', 'Para a parede', 'Painéis em relevo, relógios e molduras.', 2),
  ('mesa-e-estante', 'Para a mesa e a estante', 'Esculturas de vulto, que ficam em pé.', 3)
on conflict (slug) do nothing;

insert into public.pecas (
  numero, slug, nome, tema, descricao, historia, madeira, altura, largura, profundidade,
  peso, ano, acabamento, preco, a_partir_de, situacao, aceita_encomenda, destaque,
  colecoes, imagens, ordem
) values
  ('0002', '0002-coruja', 'Coruja', 'fauna', 'Peça de bancada, cada pena entalhada uma a uma', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['mesa-e-estante']::text[], array['/acervo/0002-coruja/01-2000.webp', '/acervo/0002-coruja/02-2000.webp']::text[], 1),
  ('0003', '0003-aguia', 'Águia', 'fauna', 'Asas abertas sobre base de tronco, tirada de um bloco só', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['mesa-e-estante']::text[], array['/acervo/0003-aguia/01-2000.webp']::text[], 2),
  ('0004', '0004-cristo-coroa-de-espinhos', 'Cristo, coroa de espinhos', 'sacra', 'Busto em madeira clara, cabelo e coroa entalhados a fundo', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['devocao', 'mesa-e-estante']::text[], array['/acervo/0004-cristo-coroa-de-espinhos/01-2000.webp']::text[], 3),
  ('0005', '0005-nossa-senhora', 'Nossa Senhora', 'sacra', 'Imagem de vulto sobre nuvens, mãos cruzadas ao peito', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['devocao', 'mesa-e-estante']::text[], array['/acervo/0005-nossa-senhora/01-2000.webp']::text[], 4),
  ('0006', '0006-oratorio-gotico', 'Oratório gótico', 'sacra', 'Capela de mesa com arcos ogivais, pináculos e imagem interna', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['devocao', 'mesa-e-estante']::text[], array['/acervo/0006-oratorio-gotico/01-2000.webp', '/acervo/0006-oratorio-gotico/02-2000.webp']::text[], 5),
  ('0007', '0007-santa-ceia', 'Santa Ceia', 'sacra', 'Painel em alto-relevo, treze figuras sobre parede de pedra', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['devocao', 'parede']::text[], array['/acervo/0007-santa-ceia/01-2000.webp']::text[], 6),
  ('0008', '0008-relogio-dos-cavalos', 'Relógio dos cavalos', 'utilitaria', 'Painel em alto-relevo com dois cavalos e mostrador ao centro', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['parede']::text[], array['/acervo/0008-relogio-dos-cavalos/01-2000.webp']::text[], 7),
  ('0009', '0009-bau-entalhado', 'Baú entalhado', 'utilitaria', 'Tampa abaulada, flores em relevo na frente e nas laterais', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array[]::text[], array['/acervo/0009-bau-entalhado/01-2000.webp']::text[], 8),
  ('0010', '0010-moldura-de-folhagem', 'Moldura de folhagem', 'utilitaria', 'Moldura vazada, folhas e volutas nos quatro cantos', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0010-moldura-de-folhagem/01-1280.webp']::text[], 9),
  ('0011', '0011-face-de-cristo', 'Face de Cristo', 'sacra', 'Coluna entalhada, traço estilizado e simétrico', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['devocao', 'mesa-e-estante']::text[], array['/acervo/0011-face-de-cristo/01-2000.webp']::text[], 10),
  ('0012', '0012-santa-ceia-ornamentada', 'Santa Ceia ornamentada', 'sacra', 'A mesma cena com moldura vazada de folhagem entalhada', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['devocao', 'parede']::text[], array['/acervo/0012-santa-ceia-ornamentada/01-2000.webp']::text[], 11),
  ('0013', '0013-santa-das-maos-postas', 'Santa das mãos postas', 'sacra', 'Imagem de vulto em madeira clara, manto em pregas longas', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['devocao', 'mesa-e-estante']::text[], array['/acervo/0013-santa-das-maos-postas/01-640.webp']::text[], 12),
  ('0014', '0014-santa-do-manto', 'Santa do manto', 'sacra', 'Imagem de vulto em madeira avermelhada, manto em torção', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['devocao', 'mesa-e-estante']::text[], array['/acervo/0014-santa-do-manto/01-2000.webp']::text[], 13),
  ('0015', '0015-coruja-e-face', 'Coruja e face', 'fauna', 'Duas leituras no mesmo bloco: a ave em cima, o rosto embaixo', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['mesa-e-estante']::text[], array['/acervo/0015-coruja-e-face/01-2000.webp']::text[], 14),
  ('0016', '0016-coruja-ao-luar', 'Coruja ao luar', 'fauna', 'Painel em relevo, ave no galho e a lua cheia ao fundo', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0016-coruja-ao-luar/01-2000.webp']::text[], 15),
  ('0017', '0017-peixes', 'Peixes', 'fauna', 'Painel em relevo com cardume, juncos e superfície da água', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0017-peixes/01-2000.webp']::text[], 16),
  ('0019', '0019-serpente-e-espada', 'Serpente e espada', 'fauna', 'Painel em relevo, corpo enrolado ao longo da lâmina', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0019-serpente-e-espada/01-2000.webp']::text[], 17),
  ('0020', '0020-mulher-do-chapeu', 'Mulher do chapéu', 'figura', 'Figura de vulto, vestido longo e mão na aba do chapéu', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['mesa-e-estante']::text[], array['/acervo/0020-mulher-do-chapeu/01-2000.webp']::text[], 18),
  ('0021', '0021-perfil-feminino', 'Perfil feminino', 'figura', 'Baixo-relevo em painel, cabelo resolvido em ondas largas', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0021-perfil-feminino/01-2000.webp']::text[], 19),
  ('0022', '0022-rosto-na-tora', 'Rosto na tora', 'figura', 'Relevo aberto na tora com casca, aproveitando o nó da madeira', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0022-rosto-na-tora/01-2000.webp']::text[], 20),
  ('0023', '0023-mascara', 'Máscara', 'figura', 'Vulto frontal de traço geométrico, boca e olhos vazados', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['mesa-e-estante']::text[], array['/acervo/0023-mascara/01-2000.webp']::text[], 21),
  ('0024', '0024-figura-de-pe', 'Figura de pé', 'figura', 'Vulto esguio em madeira escura, braço erguido e pano ao corpo', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['mesa-e-estante']::text[], array['/acervo/0024-figura-de-pe/01-2000.webp']::text[], 22),
  ('0025', '0025-figura-com-manto', 'Figura com manto', 'figura', 'Vulto de pé com pano cruzado, entalhado em bloco único', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['mesa-e-estante']::text[], array['/acervo/0025-figura-com-manto/01-2000.webp']::text[], 23),
  ('0026', '0026-rosa', 'Rosa', 'natureza', 'Flor aberta sobre haste, pétala por pétala, em base de tronco', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, true, array['mesa-e-estante']::text[], array['/acervo/0026-rosa/01-2000.webp']::text[], 24),
  ('0027', '0027-girassol', 'Girassol', 'natureza', 'Painel em relevo, miolo trabalhado em grão fino', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0027-girassol/01-2000.webp']::text[], 25),
  ('0028', '0028-lua', 'Lua', 'natureza', 'Painel estreito em relevo, figura recostada no quarto crescente', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0028-lua/01-2000.webp']::text[], 26),
  ('0029', '0029-relogio-cabeca-de-cavalo', 'Relógio cabeça de cavalo', 'utilitaria', 'Peça de parede recortada, crina entalhada em mechas soltas', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0029-relogio-cabeca-de-cavalo/01-2000.webp']::text[], 27),
  ('0030', '0030-relogio-de-parede', 'Relógio de parede', 'utilitaria', 'Caixa vazada com volutas e coroamento entalhado', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0030-relogio-de-parede/01-2000.webp']::text[], 28),
  ('0031', '0031-moldura-de-arabescos', 'Moldura de arabescos', 'utilitaria', 'Moldura em madeira clara, desenho contínuo em toda a volta', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0031-moldura-de-arabescos/01-2000.webp']::text[], 29),
  ('0032', '0032-moldura-com-coroamento', 'Moldura com coroamento', 'utilitaria', 'Moldura vazada com crista de folhagem acima do quadro', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['parede']::text[], array['/acervo/0032-moldura-com-coroamento/01-2000.webp']::text[], 30),
  ('0033', '0033-aguia-sobre-a-esfera', 'Águia sobre a esfera', 'fauna', 'Asas erguidas, pousada sobre uma esfera entalhada', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['mesa-e-estante']::text[], array['/acervo/0033-aguia-sobre-a-esfera/01-2000.webp']::text[], 31),
  ('0034', '0034-aguia-sobre-o-bloco', 'Águia sobre o bloco', 'fauna', 'Asas erguidas sobre um bloco retangular de madeira', null, null, null, null, null, null, null, null, null, false, 'a-venda', true, false, array['mesa-e-estante']::text[], array['/acervo/0034-aguia-sobre-o-bloco/01-2000.webp']::text[], 32)
on conflict (numero) do nothing;
